import                            = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]
live_config_reload                = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal                            = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size                              = 14

[env]
TERM                              = "xterm-256color"

[window]
decorations                       = "buttonless"
decorations_theme_variant         = "None"
dynamic_title                     = true
dynamic_padding                   = false
startup_mode                      = "Windowed"

[window.padding]
x                                 = 12
y                                 = 12

[selection]
save_to_clipboard                 = true
semantic_escape_chars             = ",│`|:\"' ()[]{}<>\t"

[cursor]
style                             = { shape = "Block", blinking = "On" }
thickness                         = 0.15
unfocused_hollow                  = true

[mouse]
hide_when_typing                  = true

[keyboard]
bindings                          = [
    # delete line command + backspace
    { key                         = "Back", mods = "Command", chars = "\u0015" },
    # delete word alt + backspace
    { key                         = "Back", mods = "Alt", chars = "\u0017" },
    # delete entire line in NVIM
    { key                         = "A", mods = "Command", chars = "\u001BggVG" },
    { key                         = "Copy", action = "Copy" },
    { key                         = "Paste", action = "Paste" },
    { key                         = "C", mods = "Command", action = "Copy" },
    { key                         = "V", mods = "Command", action = "Paste" },
    { key                         = "W", mods = "Command", action = "Quit" },
    { key                         = "Q", mods = "Command", action = "Quit" },
    { key                         = "H", mods = "Command", action = "Hide" },
]


[[hints.enabled]]
command                           = "open"
hyperlinks                        = true
post_processing                   = true
regex                             = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
mouse                             = { mods = "None", enabled = true }
