[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]

[terminal.shell]
program = "/bin/zsh"
args = [
  "--login",
  "-c",
  "/opt/homebrew/bin/tmux attach || //opt/homebrew/bin/tmux",
]

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14

[env]
TERM = "screen-256color"

[window]
decorations = "buttonless"
decorations_theme_variant = "None"
dynamic_title = true
dynamic_padding = false
startup_mode = "Windowed"
padding = { x = 6, y = 6 }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.15
unfocused_hollow = true

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[keyboard]
bindings = [
  # delete line command + backspace
  { key = "Back", mods = "Command", chars = "\u0015" },
  # delete word alt + backspace
  { key = "Back", mods = "Alt", chars = "\u0017" },
  # delete entire line in NVIM
  { key = "A", mods = "Command", chars = "\u001BggVG" },
  { key = "Copy", action = "Copy" },
  { key = "Paste", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "W", mods = "Command", action = "Quit" },
  { key = "Q", mods = "Command", action = "Quit" },
  { key = "H", mods = "Command", action = "Hide" },
  { key = "T", mods = "Command", chars = "\u0001c" },
]
