tap "buo/cask-upgrade"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

cask_args appdir: "~/Applications"

brew "curl"
brew "fd"
brew "gh"
brew "git"
brew "htop"
brew "mas"
brew "neovim"
brew "nvm"
brew "python@3.10"
brew "poetry"
brew "ripgrep"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
cask "1password"
cask "aldente"
cask "alfred"
cask "alt-tab"
cask "appcleaner"
cask "cleanshot"
cask "discord"
cask "docker"
cask "firefox"
cask "font-input"
cask "font-jetbrains-mono-nerd-font"
cask "font-sf-mono"
cask "github"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "maestral"
cask "miniforge"
cask "notion"
cask "slack"
cask "spotify"
cask "tg-pro"
cask "timche-gmail-desktop"
cask "via"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

mas install 417375580 
mas install 1569813296 
mas install 1440147259 
mas install 937984704
mas install 1452453066
