git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  border: rounded
  showBottomLine: false
  nerdFontsVersion: "3"
os:
  editPreset: "nvim"

disableStartupPopups: true
