start-at-login = true
after-login-command = []
after-startup-command = [
  'exec-and-forget borders style=round width=6.0 hidpi=on active_color=0xc0e2e2e3 inactive_color=0xc02c2e34 background_color=0x302c2e34',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = 'move-mouse window-lazy-center'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]
alt-enter = 'exec-and-forget open -a /Applications/WezTerm.app'
cmd-h = []
cmd-alt-h = []

alt-ctrl-shift-slash = 'layout tiles horizontal vertical'

cmd-alt-ctrl-shift-f = 'fullscreen'

cmd-alt-ctrl-shift-p = 'workspace-back-and-forth'
cmd-alt-ctrl-shift-n = 'workspace-back-and-forth'

cmd-alt-ctrl-shift-h = 'focus left'
cmd-alt-ctrl-shift-j = 'focus down'
cmd-alt-ctrl-shift-k = 'focus up'
cmd-alt-ctrl-shift-l = 'focus right'

alt-shift-ctrl-h = 'move left'
alt-shift-ctrl-j = 'move down'
alt-shift-ctrl-k = 'move up'
alt-shift-ctrl-l = 'move right'

alt-shift-ctrl-quote = 'resize smart -50'
alt-shift-ctrl-backslash = 'resize smart +50'

cmd-alt-ctrl-shift-m = 'workspace main'
cmd-alt-ctrl-shift-i = 'workspace info'
cmd-alt-ctrl-shift-u = 'workspace utils'
cmd-alt-ctrl-shift-s = 'workspace secondary'
cmd-alt-ctrl-shift-o = 'workspace overflow'

alt-shift-ctrl-m = 'move-node-to-workspace main'
alt-shift-ctrl-i = 'move-node-to-workspace info'
alt-shift-ctrl-u = 'move-node-to-workspace utils'
alt-shift-ctrl-s = 'move-node-to-workspace secondary'
alt-shift-ctrl-o = 'move-node-to-workspace overflow'

alt-shift-ctrl-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-ctrl-h = ['join-with left', 'mode main']
alt-shift-ctrl-j = ['join-with down', 'mode main']
alt-shift-ctrl-k = ['join-with up', 'mode main']
alt-shift-ctrl-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
main = ['Studio Display', '^built-in retina display$']
secondary = 'secondary'

# https://nikitabobko.github.io/AeroSpace/goodies#popular-apps-ids
[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'move-node-to-workspace secondary'

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace secondary'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace secondary'


[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'move-node-to-workspace secondary'


[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'move-node-to-workspace secondary'

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'move-node-to-workspace secondary'

[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = 'move-node-to-workspace secondary'


[[on-window-detected]]
if.app-id = 'com.facebook.archon.developerID'
run = 'move-node-to-workspace secondary'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace secondary'
